
import java.sql.Connection;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Windows 10
 */
public class Log extends javax.swing.JFrame {
String nama = "";
    /**
     * Creates new form Log
     */
    public Log() {
        initComponents();
        this.setResizable(false);
        this.setTitle("LOG IN");
        
        
    }
    
    public void logNama(String nama){
    String sqli = "SELECT nama FROM register WHERE username = '"+txt_user.getText()+"';";
    try{
        java.sql.Connection conn = (Connection) kon12.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sqli);
            java.sql.ResultSet rs = pst.executeQuery(sqli);
            if(rs.next()){
                nama = String.valueOf(rs.getString(1));
                System.out.println(nama);
            
            }
    }catch(Exception e){
    
        }
    }
    private void masukLogin(){
        
        String sql = "Select * From akun WHERE username = '"+txt_user.getText()+"' AND pw = '"+txt_pw.getText()+"';";
        try{
            java.sql.Connection conn = (Connection) kon12.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            if(rs.next()){
                if(txt_user.getText().toString().equals(rs.getString(1))&&
                   txt_pw.getText().toString().equals(rs.getString(2))){
                   JOptionPane.showMessageDialog(this, "BERHASIL LOGIN");
                   this.setVisible(false);
                   new MainMenu(rs.getString(1)).setVisible(true);
                
                }
            }else{
                   JOptionPane.showMessageDialog(this, "MAAF USERNAME / SANDI SALAH BOUZ!");
            }
        
        }catch(Exception e){
        
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_pw = new javax.swing.JTextField();
        txt_user = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_masuk = new javax.swing.JButton();
        btn_daftar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_lupaSndi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_pw.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 210, 30));

        txt_user.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 210, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PASSWORD :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USERNAME :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        btn_masuk.setBackground(new java.awt.Color(255, 153, 153));
        btn_masuk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_masuk.setForeground(new java.awt.Color(255, 255, 255));
        btn_masuk.setText("MASUK");
        btn_masuk.setBorder(null);
        btn_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masukActionPerformed(evt);
            }
        });
        getContentPane().add(btn_masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 90, 30));

        btn_daftar.setBackground(new java.awt.Color(102, 51, 255));
        btn_daftar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_daftar.setForeground(new java.awt.Color(255, 255, 255));
        btn_daftar.setText("DAFTAR");
        btn_daftar.setBorder(null);
        btn_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_daftarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 90, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lupa Sandi? klik-->");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, 30));

        btn_lupaSndi.setBackground(new java.awt.Color(255, 51, 51));
        btn_lupaSndi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_lupaSndi.setForeground(new java.awt.Color(255, 255, 255));
        btn_lupaSndi.setText("FORGET PW");
        btn_lupaSndi.setBorder(null);
        btn_lupaSndi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lupaSndiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lupaSndi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img12/loginfixx.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 530));

        setSize(new java.awt.Dimension(816, 525));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masukActionPerformed
        // TODO add your handling code here:
        masukLogin();
    }//GEN-LAST:event_btn_masukActionPerformed

    private void btn_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_daftarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Reg().setVisible(true);
    }//GEN-LAST:event_btn_daftarActionPerformed

    private void btn_lupaSndiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lupaSndiActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new lupaSandi().setVisible(true);
    }//GEN-LAST:event_btn_lupaSndiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Log().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_daftar;
    private javax.swing.JButton btn_lupaSndi;
    private javax.swing.JButton btn_masuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_pw;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
