import java.sql.Connection;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows 10
 */
public class SettingProfile extends javax.swing.JFrame {
    String idNama = "";
    /**
     * Creates new form SettingProfile
     */
    public SettingProfile(String username) {
        initComponents();
        setNama(username);
        this.setResizable(false);
        loadDataUser( username);
        run();
        
        
    }
    
    public void HapusAkun(){
        String sql2 = "DELETE  FROM register WHERE username = '"+txt_user.getText()+"';";
        String sql = "DELETE  FROM akun WHERE username = '"+txt_user.getText()+"';";
        System.out.println(sql);
        System.out.println(sql2);
        try{
            java.sql.Connection conn = (Connection) kon12.configDB();
            java.sql.PreparedStatement pst2 = conn.prepareStatement(sql2);
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst2.execute();
            pst.execute();
            
            JOptionPane.showMessageDialog(this, "DATA BERHASIL DIHAPUS");
            JOptionPane.showMessageDialog(this, "ANDA KELUAR DARI APPS");
            this.setVisible(false);
            new Log().setVisible(true);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    public void confirm(){
        int jawab = JOptionPane.showConfirmDialog(this, "Apakah anda Yakin ingin hapus akun");
        
        switch(jawab){
            case JOptionPane.YES_OPTION:
                HapusAkun();
                break;
            case JOptionPane.NO_OPTION:
                JOptionPane.showMessageDialog(this, "Silakan Kembali beraktifitas");
                break;
            case JOptionPane.CANCEL_OPTION:
                 JOptionPane.showMessageDialog(this, "BATAL OKE");
                 break;   
        }
    }
    
    public void editable(){
        txt_nama.setEditable(true);
        txt_alamat.setEditable(true);
        txt_telephone.setEditable(true);
        
    }
    
    public void NonEditable(){
        txt_nama.setEditable(false);
        txt_alamat.setEditable(false);
        txt_telephone.setEditable(false);
    
    }
    
    public void setNama(String user){
    username1.setText(user);
    idNama = String.valueOf(user);
    }
    
    public void run(){
        SimpleDateFormat format =  new SimpleDateFormat ("EEEE , dd MMMM yyyy");
        java.util.Date date = new java.util.Date();
        tanggalan.setText(format.format(date));
        System.out.println(date);
    }
    
    public void loadDataUser(String user1){
        setNama(user1);
        String sql = "SELECT * FROM register WHERE username = '"+user1+"';";
        System.out.println(sql);
        try{
            java.sql.Connection conn = (Connection) kon12.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();
            while(rs.next()){
                txt_user.setText(rs.getString(1));
                txt_nama.setText(rs.getString(2));
                txt_alamat.setText(rs.getString(3));
                txt_telephone.setText(rs.getString(4));
                
            }
            
        }catch(Exception e){
        
        }
    }
    
    public void SimpanData(){
        String sql= "Update register SET nama ='"+txt_nama.getText()+"',"
                + "alamat ='"+txt_alamat.getText()+"',Phone ='"+txt_telephone.getText()+"' WHERE username = '"+txt_user.getText()+"';";
        System.out.println(sql);
        try{
            java.sql.Connection conn = (Connection) kon12.configDB();
            java.sql.PreparedStatement pst1 = conn.prepareStatement(sql);
            pst1.execute();
            JOptionPane.showMessageDialog(this, "Data Berhasil Di Ubah");
        }catch(Exception e){
        
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txt_user = new javax.swing.JTextField();
        txt_telephone = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tanggalan = new javax.swing.JLabel();
        btn_edit = new javax.swing.JButton();
        btn_Keluar = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_setting = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 180, 40));

        username1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        username1.setForeground(new java.awt.Color(255, 255, 255));
        username1.setText("jLabel2");
        getContentPane().add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        txt_user.setEditable(false);
        txt_user.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_user.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 370, 30));

        txt_telephone.setEditable(false);
        txt_telephone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_telephone.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txt_telephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 370, 30));

        txt_nama.setEditable(false);
        txt_nama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_nama.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 370, 30));

        txt_alamat.setEditable(false);
        txt_alamat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_alamat.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 370, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TELEPHONE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 120, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USERNAME ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 120, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NAMA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 120, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ALAMAT");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 120, 30));

        tanggalan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tanggalan.setForeground(new java.awt.Color(0, 0, 0));
        tanggalan.setText("TANGGALAN");
        getContentPane().add(tanggalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 190, 20));

        btn_edit.setBackground(new java.awt.Color(255, 102, 102));
        btn_edit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setText("EDIT DATA");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 120, 30));

        btn_Keluar.setBackground(new java.awt.Color(255, 102, 102));
        btn_Keluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Keluar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Keluar.setText("KELUAR");
        btn_Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 120, 30));

        btn_simpan.setBackground(new java.awt.Color(255, 102, 102));
        btn_simpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setText("SIMPAN DATA");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, 120, 30));

        btn_hapus.setBackground(new java.awt.Color(255, 102, 102));
        btn_hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("HAPUS AKUN");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, 120, 30));

        jPanel2.setBackground(new java.awt.Color(44, 53, 80));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 210, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, 600, 30));

        btn_setting.setContentAreaFilled(false);
        btn_setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_settingActionPerformed(evt);
            }
        });
        getContentPane().add(btn_setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 180, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img12/Setting Profile 2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(864, 685));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainMenu(username1.getText()).setVisible(true);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        editable();
        
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KeluarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainMenu(username1.getText()).setVisible(true);
    }//GEN-LAST:event_btn_KeluarActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        SimpanData();
        NonEditable();
        
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        confirm();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_settingActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Setting(username1.getText()).setVisible(true);
    }//GEN-LAST:event_btn_settingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingProfile(username1.getText()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Keluar;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_setting;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel tanggalan;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_telephone;
    private javax.swing.JTextField txt_user;
    public static final javax.swing.JLabel username1 = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
