import java.sql.*;
import java.text.SimpleDateFormat;

/**
 *
 * @author Windows 10
 */
public class thisDay extends javax.swing.JFrame {

    /**
     * Creates new form thisDay
     */
    public thisDay(String username) {
        initComponents();
        this.setResizable(false);
        totalPenjualabThisDay();
        setNama(username);
        namaAn(username);
        run();
    }
    
    public void totalPenjualabThisDay(){
        int totalPenjualan = 0;
        int totalPembeli = 0;
        int totalBrgSold = 0;
        String sql = "SELECT * FROM penjualan WHERE waktu = CURDATE();";
        try{
            Connection conn = (Connection) kon12.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet res = pst.executeQuery();
        while(res.next()){
            totalPenjualan += Integer.parseInt(res.getString(2));
            totalBrgSold += Integer.parseInt(res.getString(3));
            totalPembeli++;
            totalPenj.setText("Rp. "+String.valueOf(totalPenjualan)+".00");
            totalPembelian.setText(String.valueOf(totalPembeli));
            totalBrg.setText(String.valueOf(totalBrgSold));
            
        
        }
        }catch(Exception e){}
    }
    
    public void setNama(String user){
    userr.setText(user);
    }
    
    public void namaAn(String useran){
    setNama(useran);
    String nama = "";
        String sql = "SELECT * FROM register WHERE username = '"+useran+"';";
        System.out.println(sql);
        try{
            java.sql.Connection conn = (Connection) kon12.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();
            while(rs.next()){
                nama = String.valueOf(rs.getString(2));
                setNamaan.setText("Hay, Selamat Datang "+nama+" Semangat..!!");
                
            }
            
        }catch(Exception e){
        
        }
    }
    
    public void run(){
        SimpleDateFormat format =  new SimpleDateFormat ("EEEE , dd MMMM yyyy");
        java.util.Date date = new java.util.Date();
        tanggalan.setText(format.format(date));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalPenj = new javax.swing.JLabel();
        totalBrg = new javax.swing.JLabel();
        totalPembelian = new javax.swing.JLabel();
        Btn_back = new javax.swing.JButton();
        setNamaan = new javax.swing.JLabel();
        tanggalan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalPenj.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        totalPenj.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(totalPenj, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 410, 160));

        totalBrg.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        totalBrg.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(totalBrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 150, 120));

        totalPembelian.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        totalPembelian.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(totalPembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 120, 120));

        userr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userr.setForeground(new java.awt.Color(255, 255, 255));
        userr.setText("jLabel2");
        getContentPane().add(userr, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 14, 120, -1));

        Btn_back.setBackground(new java.awt.Color(255, 153, 153));
        Btn_back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btn_back.setForeground(new java.awt.Color(255, 255, 255));
        Btn_back.setText("KEMBALI");
        Btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 610, 110, 30));

        setNamaan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        setNamaan.setForeground(new java.awt.Color(255, 255, 255));
        setNamaan.setText("jLabel2");
        getContentPane().add(setNamaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 640, 40));

        tanggalan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tanggalan.setForeground(new java.awt.Color(255, 255, 255));
        tanggalan.setText("TANGGALAN");
        getContentPane().add(tanggalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 190, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img12/Hari ini.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(865, 687));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainMenu(userr.getText()).setVisible(true);
    }//GEN-LAST:event_Btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(thisDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(thisDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(thisDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(thisDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new thisDay(userr.getText()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel setNamaan;
    private javax.swing.JLabel tanggalan;
    private javax.swing.JLabel totalBrg;
    private javax.swing.JLabel totalPembelian;
    private javax.swing.JLabel totalPenj;
    public static final javax.swing.JLabel userr = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
